AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pre-requisites-resources

  SAM Template for pre-requisites resources


Resources:
  ShoppingCartSrcS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-serverless-shopping-cart-src-$(ACCOUNT_ID)-$(REGION)

Outputs:
  Auth_S3_bucket:
    Description: "Shopping cart source s3"
    Value: !Ref ShoppingCartSrcS3
